export const types = {
	ADD_TODO_ITEM: 'ADD_TODO_ITEM',
	REMOVE_TODO_ITEM: 'REMOVE_TODO_ITEM',

	GET_PROFILES_REQUEST: 'GET_PROFILES_REQUEST',
	GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
	GET_PROFILES_FAILURE: 'GET_PROFILES_FAILURE'
};
